### ISSUE TITLE
Prevent optional chaining `foo?.bar`?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-project-boilerplate#179]
In the past, we had problems with browser support for optional chaining (the `foo?.bar` syntax) and I've been seeing it a few times in PRs I reviewed.

Is this still an ongoing concern?

Should be try to catch it early through an eslint rule?

**Comment by davidnuescheler** [comment]
hmm... i am generally not in favor of custom linting configs, but i just saw this a couple of days ago in code, so i'd be open to it. maybe @ramboz has an opinion.

**Comment by ramboz** [comment]
I would say this is valid modern JS and also has pretty good browser support by now (see https://caniuse.com/mdn-javascript_operators_optional_chaining). Since we kinda claim that Franklin lets you use the latest JS best practices out of the box, I would definitely not block it.

I would only see an issue if the project we are working on is targeting older browsers as well, but that is then a project-specific constraint I'd handle locally via linting rules overrides.
